# enable mouse support
set -g mouse on

unbind -T prefix M-Up
unbind -T prefix M-Down

# macos: map ⌥ + <- ->  to cursor movement
unbind -T prefix M-Left
unbind -T prefix M-Right
bind -n M-Left send-keys C-Left
bind -n M-Right send-keys C-Right
